# Generated by Django 5.0.2 on 2024-02-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_avatar_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(choices=[('User', 'User'), ('Moderator', 'Moderator')], default='User', max_length=15),
        ),
    ]
